-- AlterTable
ALTER TABLE `fields` MODIFY `type` ENUM('TEXT', 'TEXTAREA', 'RADIO', 'CHECKBOX', 'SELECT', 'DATE', 'TIME', 'DATETIME', 'EMAIL', 'NUMBER', 'PASSWORD', 'FILE', 'HIDDEN', 'COLOR', 'RANGE', 'TEL', 'URL', 'SEARCH', 'MONTH', 'WEEK', 'IMAGE', 'BUTTON', 'SUBMIT', 'RESET', 'BOOLEAN') NOT NULL DEFAULT 'TEXT';
